# Generated by Django 5.0.3 on 2024-11-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='value_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('national_ID', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=11)),
                ('approval', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
