# Generated by Django 5.0.3 on 2024-11-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_value_db_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value_db',
            name='mail',
            field=models.EmailField(default='default@example.com', max_length=200, unique=True),
        ),
    ]
