# Generated by Django 5.0.3 on 2024-11-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_value_db_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value_db',
            name='approval',
            field=models.IntegerField(default=0),
        ),
    ]
