# Generated by Django 5.0.3 on 2024-11-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_value_db_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value_db',
            name='national_ID',
        ),
    ]
